name: zuda-backend-deploy

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: yarn
      - run: yarn lint

  build:
    needs: lint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@master
      - run: yarn
      - run: yarn build
      - name: Branch tag
        id: branch_tag
        run: |
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}
      - run: docker login ghcr.io -u ${{ secrets.GH_USER }}
          -p ${{ secrets.GH_TOKEN }}
      - run: docker build -t ghcr.io/zzuda/zuda-backend:latest
          -t ghcr.io/zzuda/zuda-backend:${{ steps.branch_tag.outputs.TAG }} .
      - run: docker push ghcr.io/zzuda/zuda-backend --all-tags
